<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.hisouten.mall</groupId>
        <artifactId>HisoutenMall</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>HisoutenMall-server</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>cn.hisouten.mall</groupId>
            <artifactId>HisoutenMall-module-account</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hisouten.mall</groupId>
            <artifactId>HisoutenMall-module-product</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hisouten.mall</groupId>
            <artifactId>HisoutenMall-module-trade</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hisouten.mall</groupId>
            <artifactId>HisoutenMall-module-marketing</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>cn.hisouten.mall.server.HisoutenMallServerApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>